App\Entities\Comment:
    type: entity
    table: comment
    repositoryClass: App\Repositories\CommentRepository

    id:
        id:
            type: integer
            generator:
                strategy: auto

    fields:
        comment:
            type: text
            length: 64000

        createdBy:
            type: string
            length: 255

        createdOn:
            type: datetime

    manyToOne:
        story:
            targetEntity: App\Entities\Story
            inversedBy: comments
            cascade: [ 'persist' ]
            joinColumn:
                onDelete: CASCADE